# Generated by Django 3.1.4 on 2021-09-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creditadjustmentreceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=25)),
                ('receipt_date', models.DateField()),
                ('date', models.DateField(auto_now=True)),
                ('adjustment_credit_amount', models.CharField(max_length=25)),
                ('reason', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='deiptadjustmentreceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=25)),
                ('receipt_date', models.DateField(auto_now=True)),
                ('date', models.DateField()),
                ('adjustment_deipt_amount', models.CharField(max_length=25)),
                ('reason', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='fineadjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=25)),
                ('date', models.DateField(auto_now=True)),
                ('fine_date', models.DateField()),
                ('fine_amout', models.DateField(max_length=10)),
                ('reason', models.CharField(max_length=25)),
            ],
        ),
    ]
