# Generated by Django 3.1.4 on 2021-07-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_type', models.CharField(max_length=15)),
                ('customer_name_payment', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=25)),
                ('customer_dateofbirth', models.DateField(blank=True)),
                ('customer_sex', models.CharField(max_length=10)),
                ('customer_createdate', models.DateField(auto_now_add=True)),
                ('customer_phone', models.IntegerField()),
                ('customer_community', models.CharField(max_length=20)),
                ('customer_Doorno', models.CharField(max_length=25)),
                ('customer_street_name', models.CharField(max_length=25)),
                ('customer_area_name', models.CharField(max_length=25)),
                ('customer_finance_amount', models.IntegerField()),
                ('customer_paid_amount', models.IntegerField()),
                ('customer_pending_amount', models.IntegerField()),
                ('customer_acnumber', models.CharField(max_length=25)),
                ('customer_ifsc', models.CharField(max_length=25)),
                ('customer_bankname', models.CharField(max_length=25)),
                ('customer_brach', models.CharField(max_length=25)),
                ('customer_pannumber', models.CharField(max_length=15)),
                ('customer_occupations', models.CharField(max_length=20)),
                ('customer_idproof', models.ImageField(upload_to='')),
                ('customer_photo', models.ImageField(upload_to='')),
                ('pending_flag', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMItype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMItype_name', models.CharField(max_length=20)),
                ('EMI_daylength', models.IntegerField()),
                ('EMi_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='monthlyloancreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlylan_customer_name', models.CharField(max_length=25)),
                ('monthlylan_EMItype', models.CharField(max_length=25)),
                ('monthlylan_sourcetype', models.CharField(max_length=25)),
                ('monthlylan_date', models.DateField(auto_now_add=True)),
                ('monthlylan_amount', models.IntegerField()),
                ('monthlylan_totalweek', models.IntegerField()),
                ('monthlylan_weeklyEMI', models.IntegerField()),
                ('monthlylan_firstemidate', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='pendingfine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_customer', models.CharField(max_length=25)),
                ('fine_date', models.DateField()),
                ('fine_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='receiptamount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_receipter_name', models.CharField(max_length=25)),
                ('loan_name', models.CharField(max_length=25)),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('receipt_emi_date', models.DateField(blank=True)),
                ('receipt_amount', models.IntegerField()),
                ('receipt_discretion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sourcetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcetype_name', models.CharField(max_length=25)),
                ('source', models.CharField(max_length=15)),
                ('source_amount', models.IntegerField()),
                ('source_discretion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='updatedate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='weeklydemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeklydemand_loan_name', models.CharField(max_length=25)),
                ('emi_amount', models.IntegerField()),
                ('emi_demand_date', models.DateField(blank=True)),
                ('pending_flag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='weeklyloancreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeklylan_customer_name', models.CharField(max_length=25)),
                ('weeklylan_loan_name', models.CharField(max_length=25)),
                ('weeklylan_EMItype', models.CharField(max_length=20)),
                ('weeklylan_sourcetype', models.CharField(max_length=20)),
                ('weeklylan_date', models.DateField(auto_now_add=True)),
                ('weeklylan_date_demant', models.DateField()),
                ('weeklylan_amount', models.IntegerField()),
                ('weeklylan_totalweek', models.IntegerField()),
                ('weeklylan_weeklyEMI', models.IntegerField()),
                ('pending_flag', models.IntegerField(blank=True)),
                ('total_receipt_amount', models.IntegerField()),
                ('total_fine_amount', models.ImageField(upload_to='')),
            ],
        ),
    ]
