# Generated by Django 3.1.4 on 2021-07-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyloancreate',
            name='per_day_fine',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
