# Generated by Django 3.1.4 on 2021-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_weeklyloancreate_per_day_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyloancreate',
            name='total_fine_amount',
            field=models.IntegerField(),
        ),
    ]
