# Generated by Django 3.1.4 on 2021-08-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_auto_20210730_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyloancreate',
            name='homeloanifo',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyloancreate',
            name='loan_phone_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyloancreate',
            name='lone_type',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyloancreate',
            name='prof',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
