# Generated by Django 3.1.4 on 2021-08-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_auto_20210813_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyloancreate',
            name='autofinace',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
