# Generated by Django 3.1.4 on 2021-10-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_weeklyloancreate_autofinace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyloancreate',
            old_name='monthlylan_weeklyEMI',
            new_name='loan_phone_no',
        ),
        migrations.AddField(
            model_name='monthlyloancreate',
            name='autofinace',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyloancreate',
            name='homeloanifo',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyloancreate',
            name='lone_type',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyloancreate',
            name='monthlylan_agreement_peride',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyloancreate',
            name='monthlylan_loan_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyloancreate',
            name='pending_flag',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyloancreate',
            name='per_day_fine',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyloancreate',
            name='prof',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyloancreate',
            name='total_fine_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyloancreate',
            name='total_receipt_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
